version: '3.7'

services:
  api:
    build: ./app
    restart: always
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000 
    volumes:
      - ./app/:/opt/python-projects/app/
      - type: bind
        source: ./token.json
        target: /opt/python-projects/app/token.json
    ports:
      - 8004:8000
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -s -f http://localhost:8000/api/v1/ping || exit 1"]
      interval: 60s
      timeout: 1s
      retries: 3